services:
  frontend:
    build:
      context: frontend
      target: prod
    env_file: ./frontend/.env.prod.sample
    ports:
      - "80:5000"
    networks:
      - frontend-backend
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: backend
      target: prod
    env_file: ./backend/.env.prod.sample
    expose:
      - "5000"
    networks:
      - frontend-backend
      - backend-db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo:6.0
    expose:
      - "27017"
    volumes:
      - db-data:/data/db
    networks:
      - backend-db
    restart: unless-stopped

networks:
  frontend-backend:
  backend-db:

volumes:
  db-data:
